import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/css'
import './Slider.scss'

const Slider = () => {
    return (
        <Swiper spaceBetween={50} slidesPerView={3} className="mySwiper">
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl1.jpg"
                    alt="Slide-1"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl2.jpg"
                    alt="Slide-2"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl3.jpg"
                    alt="Slide-3"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl4.jpg"
                    alt="Slide-4"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl5.jpg"
                    alt="Slide-5"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl6.jpg"
                    alt="Slide-6"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl7.jpg"
                    alt="Slide-7"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl8.jpg"
                    alt="Slide-8"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl9.jpg"
                    alt="Slide-9"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl10.jpg"
                    alt="Slide-10"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl11.jpg"
                    alt="Slide-11"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl12.jpg"
                    alt="Slide-12"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl13.jpg"
                    alt="Slide-13"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl14.jpg"
                    alt="Slide-14"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl15.jpg"
                    alt="Slide-15"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl16.jpg"
                    alt="Slide-16"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl17.jpg"
                    alt="Slide-17"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl18.jpg"
                    alt="Slide-18"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl19.jpg"
                    alt="Slide-19"
                />
            </SwiperSlide>
            <SwiperSlide>
                <img
                    src="https://raw.githubusercontent.com/DiKey100/control-project-03.02/master/public/images/slider/sl20.jpg"
                    alt="Slide-20"
                />
            </SwiperSlide>
        </Swiper>
    )
}

export default Slider
